ALTER TABLE review
   ADD COLUMN content_hash VARCHAR(64),
   ALTER COLUMN hotel_review_id TYPE VARCHAR(100),
   ALTER COLUMN provider_external_id TYPE VARCHAR(100),
   ALTER COLUMN rating TYPE DOUBLE PRECISION,
   ADD COLUMN version BIGINT NOT NULL DEFAULT 1;
